name: deploy blog to tengxunyun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@main
      
      # Deploy
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: 'nkcs@82.156.168.246'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: /home/nkcs/autoDeploy.sh

